// Generated by https://quicktype.io

export interface TeamRes {
    team_uid:               string;
    description:            string;
    entity_uid:             string;
    players_assigned:       number;
    entity_name:            string;
    categories:             string[];
}
